pub mod write;
pub mod config;

pub enum VilogCommandKind {
    LineTo                  =  0,
    MoveTo                  =  1,
    QuaraticCurveTo         =  2,
    BezierCurveTo           =  3,
    Arc                     =  4,
    ArcTo                   =  5,
    Fill                    =  6,
    ClosePath               =  7,
    DrawCircle              =  8,
    DrawEllipse             =  9,
    DrawRectangle           = 10,
    DrawRoundRectagle       = 11,
    DrawRegularPolygon      = 12,
    DrawStar                = 13,
    DrawGrid                = 14,
    DrawColumns             = 15,
    MultiplyTranform        = 16,
    ResetTranform           = 17,
    MultiplyAlpha           = 18,
    ResetAlpha              = 19,
    SetLineAlpha            = 20,
    SetFillAlpha            = 21,
    SetLineColor            = 22,
    SetFillColor            = 23,
    SetLineThickness        = 24,
    SetBlendMode            = 25,
    SetLineAlignment        = 26,
    SetFonts                = 27,
    SetFontSize             = 28,
    SetFontStyle            = 29,
    SetTextHorizontalAlign  = 30,
    SetTextVerticalAlign    = 31,
    DrawText                = 32,
    SetImageHorizontalAlign = 33,
    SetImageVerticalAlign   = 34,
    DrawImage               = 35,
    StartMaskingRegion      = 36,
    StartMaskedRegion       = 37,
    EndMaskRegion           = 38,
    ReferenceCommands16_8   = 39,
    ReferenceCommands24_16  = 40,
    ReferenceCommands32_24  = 41,
    ArrowTo                 = 42,
    CurveArrowTo            = 43,
    ArcArrowTo              = 44,
}

pub enum BlendMode {
    Normal     = 0 ,
    Add        = 1 ,
    Multiply   = 2 ,
    Screen     = 3 ,
    Overlay    = 4 ,
    Darken     = 5 ,
    Lighten    = 6 ,
    ColorDodge = 7 ,
    ColorBurn  = 8 ,
    HardLight  = 9 ,
    SoftLight  = 10,
    Difference = 11,
    Exclusion  = 12,
    Hue        = 13,
    Saturation = 14,
    Color      = 15,
    Luminosity = 16,
}
